### ISSUE TITLE
Inquiry

### ISSUE THREAD

**Issue by kcelestinomaria** [aurora-is-near/eth-connector#13]
@artob , @mrLSD , @djsatok , @sept-en , @abacabadabacaba , hello, are you working on an ERC-20 connector as well on this project?

**Comment by mfornet** [comment]
Do you mean transferring NEAR as an ERC20 to Ethereum? If that is the case then the connector is being implemented here: https://github.com/aurora-is-near/near-erc20-connector/pull/1

**Comment by kcelestinomaria** [comment]
Yes, hm, let me check it out. Thank you @mfornet
